language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - cd social-server-api
  - chmod +x mvnw

script: "./mvnw clean package"


before-deploy:
  - zip -r sns-service *
  - mkdir -p deploy
  - mv sns-service.zip deploy/sns-service.zip


deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: sns-service
    region: ap-northeast-2
    skip-cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: sns-service
    key: sns-service.zip
    bundle_type: zip
    application: sns-service
    deployment_group: sns-service-group
    region: ap-northeast-2
    wait-until-deployed: true

notifications:
  email:
    recipients:
      -iws1605@naver.com