language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - cd social-server-api
  - chmod +x mvnw

script: "./mvnw clean package"

notifications:
  email:
    recipients:
      -iws1605@naver.com
